[package]
name = "verta_project_v2"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.18.26"  
solana-client = "1.18.26"  
solana-program = "1.18.26"  
tokio = { version = "1.0", features = ["full"] }  
borsh = "0.10"
borsh-derive = "0.10"